### ISSUE TITLE
Only first language in a list of languages is working

### ISSUE THREAD

**Issue by nataliGitHub** [rominf/profanity-filter#13]
```python
>>> pf = ProfanityFilter(languages=['en', 'ru'])
>>> pf.censor_whole_words=False
>>> pf.censor("goodshiit")
'good*****'
>>> pf.censor("улицабля")
'улицабля'

>>> pf = ProfanityFilter(languages=['ru', 'en'])
>>> pf.censor_whole_words=False
>>> pf.censor("улицабля")
'улица***'
>>> pf.censor("goodshiit")
'goodshiit'
```

**Comment by rominf** [comment]
Cannot reproduce:

```python
In [1]: from profanity_filter import ProfanityFilter

In [2]: pf = ProfanityFilter(languages=['ru', 'en'])

In [3]: pf.censor_whole_words = False

In [4]: pf.censor("улицабля")
Detector is not able to detect the language reliably.
Out[4]: 'улица***'

In [5]: pf.censor("goodshiit")
Out[5]: 'good*****'
```

Make sure that you've followed [documentation](https://github.com/rominf/profanity-filter#multilingual-support) correctly.

**Comment by nataliGitHub** [comment]
After polyglot was installed correctly based on matching icu4c and pyicu it started to work. I am sorry for false alarm.

**Comment by rominf** [comment]
It's OK. Difficulties mean that probably I should make separate functions, which import things and shows traceback. That's on my list of things to do first.

**Comment by nataliGitHub** [comment]
yeah, 'import polyglot' was successful but I would never guess to try 'import polyglot.detect' to troubleshoot. Thanks for the hint.

**Comment by rominf** [comment]
I've added instructions for troubleshooting: https://github.com/rominf/profanity-filter#troubleshooting. Now everything should be fine.
