### ISSUE TITLE
TypeError when calling extra_profane_word_dictionaries

### ISSUE THREAD

**Issue by eevelweezel** [rominf/profanity-filter#21]
When supplying a dict ({lang: {set}}) to extra_profane_word_dictionaries, it raises a TypeError after trying to divide a string by a string:

`Traceback (most recent call last):
  File "<console>", line 4, in <module>
  File "/home/hwhite/frac37/lib/python3.7/site-packages/profanity_filter/profanity_filter.py", line 265, in custom_profane_word_dictionaries
    self.clear_cache()
  File "/home/hwhite/frac37/lib/python3.7/site-packages/profanity_filter/profanity_filter.py", line 384, in clear_cache
    self._update_profane_word_dictionary_files()
  File "/home/hwhite/frac37/lib/python3.7/site-packages/profanity_filter/profanity_filter.py", line 429, in _update_profane_word_dictionary_files
    profane_word_file = self._DATA_DIR / f'{language}_profane_words.txt'
TypeError: unsupported operand type(s) for /: 'str' and 'str'`

**Comment by rominf** [comment]
Cannot reproduce. Have you changed `_DATA_DIR` to `str`? Could you please send a minimal working example, that reproduces an issue?

**Comment by rominf** [comment]
Closing due inactivity. Feel free to open it again.

**Comment by hcao2015** [comment]
Hi, I encountered the same bug above. 
` File "/home/hc/projects/fm_env/lib/python3.7/site-packages/profanity_filter/profanity_filter.py", line 375, in spells
    self._spells[language] = HunSpell(self._DATA_DIR / f'{language}.dic',
TypeError: unsupported operand type(s) for /: 'str' and 'str'`

**Comment by rominf** [comment]
@hcao2015 Please attach a minimal working example.

**Comment by hcao2015** [comment]
Sorry, I figured out it was the wrong format of self._DATA_DIR that caused the problem

**Comment by rominf** [comment]
@hcao2015 you are welcome to implement #23. Sorry, but currently I don't have time for this.
