### ISSUE TITLE
Windows 10, Python 3.8 can't run console command

### ISSUE THREAD

**Issue by teebu** [rominf/profanity-filter#27]
After installing, I'm not getting the console command to work. 

```Console Executable
profanity_filter -h
command not found

```

It's not in my `C:\Python38\Scripts` nor my `C:\Users\abc\AppData\Roaming\Python\Python38\Scripts`

**Comment by rominf** [comment]
I don't have Windows 10 to verify, but it should be fixed now (in the latest version on PyPI).

**Comment by teebu** [comment]
Can confirm, the exe is now found in `/c/Python38/Scripts/profanity_filter`.
