### ISSUE TITLE
Invalid syntax in profanity_filter.py Class config

### ISSUE THREAD

**Issue by tonmoyborah** [rominf/profanity-filter#3]
Hi @rominf 
When I do

    from profanity_filter import ProfanityFilter as pf
    pf.censor("That's bullshit!")

This error pops
    SyntaxError: invalid syntax in File "/usr/local/lib/python3.5/dist-packages/profanity_filter/profanity_filter.py", line 102
    censor_char: str = '*'

    
Is this a python3 issue? Does this only support python 2?

**Comment by tonmoyborah** [comment]
This requires python>3.6 I realised

**Comment by rominf** [comment]
Yep: 
![PyPI Python version requirements](https://user-images.githubusercontent.com/3449635/49862186-aec5dc80-fe0e-11e8-976e-77158cbbb5d5.png)
