### ISSUE TITLE
Fails to detect phrases

### ISSUE THREAD

**Issue by tonmoyborah** [rominf/profanity-filter#4]
Hi,
Am I correct in assuming that this library can not censor phrases like "2 girls 1 cup" where individual words are harmless but the sentence is suggestive even if I add them to `custom_profane_word_dictionaries`?
Thanks

**Comment by tonmoyborah** [comment]
Is there any way you can point me to change something that makes this possible? Or any other python project you know which does this?

**Comment by rominf** [comment]
> Is there any way you can point me to change something that makes this possible?

I don't know right now how to implement this.

>  Or any other python project you know which does this?

I'm not aware of such project.
