### ISSUE TITLE
Show real profane word to a user

### ISSUE THREAD

**Issue by nataliGitHub** [rominf/profanity-filter#7]
Hi Roman,
Thank you for sharing a code for your product. I learned a lot from it and
find it very powerful and reliable for the amount of features it provides. Did not try all of them yet though. :)

Have a suggestion.
Can we bring up the bad_word that was mutated by the user into result? 
Ex, if I have "shiiiit" as an input, I would want to know what was the real bad_word that Levenshtein "had in mind" ("shit"). This example is easy but sometimes there are cases when you cannot even guess why the word is censored.
Do you see a value in it? Do you think it makes sense to add it? Maybe by extra parameter if not always?

Thank you very much for being very responsive and providing an excellent support for your great product!

**Comment by rominf** [comment]
I think the best way to implement it is not to clutter existing functions but to add a new function. The usage will look like:
```python
from profanity_filter import ProfanityFilter
pf = ProfanityFilter()
pf.original_profane_word('hi')  # returns None as it's not profane
pf.original_profane_word('shiiiit')
# 'shit'
```

What do you think?

PS: thank you for kind words!

**Comment by nataliGitHub** [comment]
yes, additional function is good, user can call it to modify a result if he/she wants to.

**Comment by rominf** [comment]
On the other hand, probably it's not enough: you have to know for which word do you want to know the original profane word.

I think it would be nice and not very hard to create a Spacy extension for profanity filtering. I imagine it should work like this:
```python
import spacy             
from profanity_filter import ProfanityFilter

pf = ProfanityFilter()
nlp = spacy.load('en')
nlp.add_pipe(pf.spacy_component, last=True)
doc = nlp('hi, shiiiit')
for token in doc:
    print(token, token._.censored, token._.original_profane_word)
# hi hi None
# , , None
# shiiiit ******* shit
```

You can read about implementation and why I used `token._.censored` instead of `token.censored` here: https://spacy.io/usage/processing-pipelines#custom-components-attributes

What do you think?

**Comment by rominf** [comment]
The question about integration with Spacy remains: whether I should tokenize the input or not, and where (before or after tokenizer) to put my component.

On the one hand, it's logical to put it the last, so that not to do tokenization step once again. On the other hand, then `sh1t` will be censored as `***t`, because the profanity filter component will receive `sh1` and `t` as tokens.

I think the answer to it is to create two components:
```python
nlp.add_pipe(pf.spacy_component_first, first=True) # slower, but capable of filtering `sh1t` correctly
# or
nlp.add_pipe(pf.spacy_component_last, last=True) # faster
```

**Comment by nataliGitHub** [comment]
Regarding the additional function...
For my use case I have to process list of strings like this "XXXXX C YYYYYY shiiiit 1234 R W ZZZZZ biiiitch ".
So I added censor_list() function that calls censor() for each list's element.
I would expect to get something like this for example element:
"XXXXX C YYYYYY ******* 1234 R W ZZZZZ ********"  Profane words: shiiiit (shit), biiiitch (bitch).

So for this use case having a function as you said is not enough, if I call it where I need it, it will be unnecessary overhead since the bad word is known already, it is not a cheap call and calculate it one more time would be weird.

One of the examples where it is hard to understand why the word was censored, is 'shasiajones@yahoo.com'

I know I did not answer all your questions. Just wanted to describe my scenario. Let me look at why you used token._.censored, did not have a chance yet.

**Comment by rominf** [comment]
> So for this use case having a function as you said is not enough, if I call it where I need it, it will be unnecessary overhead since the bad word is known already, it is not a cheap call and calculate it one more time would be weird.

I already use caching. If I add original profane word saving, I will use it too. So, if, for example, you call:
```python
pf.censor('That is shiiiit')
pf.original_profane_word('shiiiit')
```
There will be almost no overhead. The second function will just use the value from the cache.

So, i think additional function will not harm, but it's just not enough.

**Comment by rominf** [comment]
@nataliGitHub, please try the latest version on PyPI with a new function `censor_word`:
```python
from profanity_filter import ProfanityFilter
pf = ProfanityFilter()
word = pf.censor_word('shiiit')
word
# Word(uncensored='shiiit', censored='******', original_profane_word='shit')
str(word)
# '******'
```

**Comment by rominf** [comment]
I'm not sure I selected the best naming. Probably it would be more consistent to do this:
```python
...
pf.censor_word('shiiit')
# CensoredWord(uncensored='shiiit', censored='******', original_profane_word='shit')
```

What do you think?

**Comment by rominf** [comment]
> One of the examples where it is hard to understand why the word was censored, is '[shasiajones@yahoo.com](mailto:shasiajones@yahoo.com)'

It's because of `hoor` (`whore`) (`yaHOO.`). I think I have to write the code to handle emails and URLs in a special way.

**Comment by nataliGitHub** [comment]
Wow, great progress!

I think uncensored is better that just word. Not sure we need censored
because it's always the same, doesn't bring additional information. Could
be wrong though.

Will try it today.

Thank you!

**Comment by rominf** [comment]
> Not sure we need censored because it's always the same, doesn't bring additional information.

We need it, as the library is capable to censor words partly.
